arguments:
  parameters:
    - name: application-name-dev-u
      value: atlastestapp-dev
    - name: revision-u
      value: main
    - name: argocd-server-address-u
      value: 192.168.64.13:30711
    - name: argocd-credentials-secret-u
      value: argocd-user
